"""add ads related tables

Revision ID: 0d1c6d5abb80
Revises: ae104320c956
Create Date: 2025-03-27 11:30:39.598729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1c6d5abb80'
down_revision: Union[str, None] = 'ae104320c956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_category_id'), 'sub_category', ['id'], unique=False)
    op.create_index(op.f('ix_sub_category_name'), 'sub_category', ['name'], unique=False)
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('negotiable', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisement_id'), 'advertisement', ['id'], unique=False)
    op.create_index(op.f('ix_advertisement_location'), 'advertisement', ['location'], unique=False)
    op.create_table('ad_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_link', sa.String(), nullable=False),
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_image_id'), 'ad_image', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_image_id'), table_name='ad_image')
    op.drop_table('ad_image')
    op.drop_index(op.f('ix_advertisement_location'), table_name='advertisement')
    op.drop_index(op.f('ix_advertisement_id'), table_name='advertisement')
    op.drop_table('advertisement')
    op.drop_index(op.f('ix_sub_category_name'), table_name='sub_category')
    op.drop_index(op.f('ix_sub_category_id'), table_name='sub_category')
    op.drop_table('sub_category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
