"""add view in advertisement

Revision ID: 68958b424fe7
Revises: 0d1c6d5abb80
Create Date: 2025-04-01 11:35:17.733177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68958b424fe7'
down_revision: Union[str, None] = '0d1c6d5abb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('views', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisement', 'views')
    # ### end Alembic commands ###
